### ISSUE TITLE
Persisting self reference relationship with both directions leads to missing relationship in DB

### ISSUE THREAD

**Issue by thePhil** [neo4j/sdn-rx#119]
Hoi,

unfortunately, I think I found a bug when trying to persist the following type of relationship:

```Java
public class Hobby {
	@Id @GeneratedValue private Long id;
	private String name;

	/**
	 * Test if reverse relationship to same node type get persisted correctly.
	 */
	@Relationship(type = "SimilarTo", inverse = "similarHobbyOf")
	private Hobby similarHobby;

	@Relationship(type = "SimilarTo", direction = Relationship.Direction.INCOMING)
	private Hobby similarHobbyOf;	

	// included to ensure empty relationships do not cause deletion
	@Relationship("EmptyRelationship")
	private List<Hobby> noHobbies;
       
// remaining class omitted
}
```
I would expect the following persistence result:
![image](https://user-images.githubusercontent.com/842122/72757040-33b52500-3bcf-11ea-9f37-5f8d315fbb6c.png)

Unfortunately I see this result (Note the missing `SimilarTo` relationship on the bottom right):
![image](https://user-images.githubusercontent.com/842122/72757113-66f7b400-3bcf-11ea-9c02-fb950d624ffe.png)

A reproducer test can be found here: https://github.com/thePhil/sdn-rx/blob/0db4928db32d8128d8020f5ea7f24bb8ded316f9/spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/imperative/RepositoryIT.java#L547 

The code in #113 also still fails the test, not sure if the resolve of #117 would also fix this bug.

**Comment by meistermeier** [comment]
Thanks for reporting this. Although #117 is only targeted for reading the outcome can hopefully be applied for the writing as well.
There are some guards in place to avoid infinite loops / recursion and resulting StackOverflows.
I will update this issue when #111 has been fixed that will also include #117 in #113 because we need to ensure that we process a reasonable amount of relationships before a guard kicks in.
