### ISSUE TITLE
DatabaseSelectionProvider points to host 0.0.0.0 when any database is selected

### ISSUE THREAD

**Issue by uberscott** [neo4j/sdn-rx#155]
The examples will work if you are running neo4j on you local machine, but if you are trying to connect to a database server that is not on the same machine it will not work.

**Comment by michael-simons** [comment]
Hi Scott. The `DatabaseSelectionProvider` is not responsible for the host the driver is connected to, it only resolves logical database names in that host or cluster.

Can you please elaborate what is not working? 

In the examples you'll have to configure the `org.neo4j.driver.uri` property accordingly.

**Comment by uberscott** [comment]
@michael-simons If the DEFAULT database is selected it will work as expected. The property org.neo4j.driver.uri will be used, if any other database is selected it will change to 0.0.0.0.  

An easy way to reproduce this would be to take the multitenant example and point it to a database that is not on the same physical computer.

**Comment by michael-simons** [comment]
I don't get it… Sorry…

https://github.com/neo4j/sdn-rx/blob/master/examples/multi-database/src/main/resources/application.properties#L19 this configures the host where the Neo4j instance is running

That property
https://github.com/neo4j/sdn-rx/blob/master/examples/multi-database/src/main/resources/application.properties#L23

configures the logical database inside that host.

So `DatabaseSelectionProvider` is only relevant for the later.

**Comment by michael-simons** [comment]
@uberscott Are you running the database on the other host via Docker?

**Comment by michael-simons** [comment]
Thanks a lot for reporting this and given us a though nut to crack. Spoiler: It's not SDN/RX.

We use the `neo4j:` protocol by default in all our examples. (ie. `org.neo4j.driver.uri=neo4j://localhost:7687`). `neo4j:` tries to request a routing table from the initial host into a Neo4j cluster and is essentially what `bolt+routing` was beforehand.

Since Neo4j 4.0 this works against single hosts as well.

So far, so good. 

The initial request against an instance on another hosts works (I tested this with an instance running via docker and direct on a host named `hades.local`) with `org.neo4j.driver.uri=neo4j://hades.local:7687`. 

When I configure SDN/RX to use the default database, nothing more happens in the initial routing context.

However, when I instruct SDN/RX to use another database (doesn't matter if I use a static method like `org.neo4j.data.database = movies` or a dynamic one via `DatabaseSelectionProvider`), a new routing table is requested from the Neo4j host I am connected to initially. 

The request for the new routing table happens in that moment when SDN/RX requests a new `Session` on the Driver. Here's the relevant log entry:

```
Routing table for database 'spring' is stale. Ttl 1583490966519, currentTime 1583490966521, routers AddressSet=[], writers AddressSet=[], readers AddressSet=[], database 'spring'
Closing connection pool towards hades.local(192.168.79.124):7687, it has no active connections and is not in the routing table registry.
Updated routing table for database 'spring'. Ttl 1583491266706, currentTime 1583490966708, routers AddressSet=[localhost:7687], writers AddressSet=[localhost:7687], readers AddressSet=[localhost:7687], database 'spring'
```

The Neo4j instance on `hades.local` is advertising `localhost` by default. A docker based instance advertises `0.0.0.0`. Both are of course not reachable from the machine where my or your SDN/RX application is running.

There are two ways to fix the situation:

1. Use `bolt://` as protocol in your application config. In my example that would be `org.neo4j.driver.uri=bolt://hades.local:7687`
2. Goto your server and configure the advertised address. You find this in `conf/neo4j.conf` under `dbms.connectors.default_advertised_address=localhost`

I hope that helps.

Thank you again for your patience and reporting this. I raised this with my colleagues from our drivers team to see whether there's room for improvement on the driver.
