### ISSUE TITLE
Getting "The mapper returned a null value."

### ISSUE THREAD

**Issue by benkuly** [neo4j/sdn-rx#240]
**Description**
When I write custom queries with `ReactiveNeo4jTemplate` or with `@Query` I get a Nullpointer with `"NullPointerException: The mapper returned a null value."`

**How to reproduce?**
You find my failing test here: https://github.com/benkuly/matrix-sms-bridge/blob/master/src/test/kotlin/net/folivo/matrix/bridge/sms/mapping/SmsRoomRepositoryIT.kt#L73
Also the other test fails, but maybe it solves, when we found a solution for this issue.

**Comment by meistermeier** [comment]
Thanks for reporting this.
Instead of not getting any response, you are getting a real `null` value back. and this will (of course) fail for an expected `Int` signal.
The supplied `someUserId` does not exist, but only `someUserId1/2`.
But in the return clause you do a `max` call with the non-existing `s.mappingToken` that creates the `null` signal instead of e.g. an empty `Mono`.
You could do something like `RETURN coalesce(max(s.mappingToken), -1)` to avoid this.

**Comment by benkuly** [comment]
Thank you very much :heart: 
`WITH max(s.mappingToken) as maxi WHERE NOT maxi IS NULL RETURN maxi` works perfect! Didn't know that there is something linke "no answer" in neo4j.
Maybe with this hint I can find more mistakes in the other not working queries.
