### ISSUE TITLE
Add @DataNeo4jTest to simplify test for Neo4j

### ISSUE THREAD

**Issue by hantsy** [neo4j/sdn-rx#36]
Like `@DataJpaTest` , `@DataMongoTest`, and try to add a neo4j special `@DataNeo4jTest` to start up just-enough beans for testing Spring data Neo4j Rx.

Currently I have created a sample for this Spring Data Neo4j Rx, https://github.com/hantsy/spring-reactive-sample/tree/master/boot-data-neo4j-rx, I have to serve a standalone Neo4j server for  test purpose. If possible, like **H2** and **EmbeddedMongo**,  add an **Embedded** Neo4j  autoconfiguration for test purpose. Thus we do not need to serve an Neo4j server to test Spring Data Neo4j Rx APIs.

**Comment by michael-simons** [comment]
Hi.
Thank you very much for trying out SDN/RX.

The test slices you're mentioning are usually part of Spring Boot and as the SDN/RX Spring Boot starter is not yet an official part (from Pivotals side of things) of Boot, we didn't add this yet.
The current one in Boot itself is only for the previous generation of SDN.

We will add this in time but it will work differently from the current one, where Neo4j-OGM is in place to start up the test server. We think this is wrong and needs to be done from the extension itself.

For the time being, we provide a Testcontainers Extension (https://www.testcontainers.org/modules/databases/neo4j/) that we are using ourselves. 
I understand however that this is additional work and tests startup slower due to the container overhead.

**Comment by michael-simons** [comment]
We will start working on this as soon as Neo4j 4.0 hits Maven central. While the MR is public available, it is not yet as libraries on a public Maven repository.

**Comment by hantsy** [comment]
Great.
