### ISSUE TITLE
Update to driver 4.0.0-beta02.

### ISSUE THREAD

**Issue by michael-simons** [neo4j/sdn-rx#56]
We need to upgrade two properties

`neo4j-java-driver.version` in `pom.xml`

and `neo4j-java-driver-spring-boot-starter.version` in `spring-data-neo4j-rx-spring-boot-starter-parent/pom.xml`

from `4.0.0-beta01` to `4.0.0-beta02`.

While this is easy, the beta02 of the driver has some subtle changes that require work in the area of closing transactions (`success` and `failure` have been consistently replaced with `commit` and `rollback`). 

I leave this as a "good first issue" and "hacktoberfest", but expect some hiccups if you grab it.

We can however help with that.

**Comment by viveksb007** [comment]
Hi @michael-simons 
updated the version, but it broke some assertions in tests because SessionConfigBuilder is not making database string lowerCase.
Now its `this.database = database;`
In previous version it was `this.database = database.toLowerCase();`

Diff of this change - https://github.com/neo4j/neo4j-java-driver/commit/e8269c2b782bee11e73a3007f9f2567520f56088#diff-229556041e09e6739d687219af7dbd42

Seems like an intentional change as tests were modified after this.
Should I fix assertions and make a PR?

**Comment by michael-simons** [comment]
Hi @viveksb007 

Yes please.
Places to look at would be

[Neo4jClientTest#verifyDatabaseSelection](org.neo4j.springframework.data.core.Neo4jClientTest#verifyDatabaseSelection)
[ReactiveNeo4jClientTest#verifyDatabaseSelection](org.neo4j.springframework.data.core.ReactiveNeo4jClientTest#verifyDatabaseSelection)

**Comment by viveksb007** [comment]
Fixed all the assertion test. But integration test are failing now due to some docker error.
`SEVERE: Caught exception while closing extension context: org.junit.jupiter.engine.descriptor.ClassExtensionContext@747edf66
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration`

What else do I need to setup locally for passing all test?

**Comment by michael-simons** [comment]
We have prepared the integration tests in such a way that one can use a locally running Neo4j instance or Docker / Testcontainers.

To test everything, including our reactive support, goto our download centre:
https://neo4j.com/download-center/?ref=blog/#prerelease

and grab either the milestone release for [Linux or Mac](https://go.neo4j.com/download-thanks-beta.html?edition=enterprise&release=4.0.0-alpha09mr02&flavour=unix) or [Windows](https://go.neo4j.com/download-thanks-beta.html?edition=enterprise&release=4.0.0-alpha09mr02&flavour=windows).

Start it (you need at least JDK11), open a browser and goto http://localhost:7474. Change the default password from `neo4j` to something of your liking. This is obligatory.

Then, go back to the SDN/RX folder and run maven like this:

```
SDN_RX_NEO4J_URL=bolt://localhost:7687 SDN_RX_NEO4J_PASSWORD=yourNewPassword ./mvnw clean verify 
```

This assumes you have a bash compatible system.
If not, you need to export `SDN_RX_NEO4J_URL` and `SDN_RX_NEO4J_PASSWORD` as environmental variables.

**Comment by viveksb007** [comment]
I think `4.0.0-beta02` version of `neo4j-java-driver-spring-boot-starter.version` is not released. I am getting following error
`Could not resolve dependencies for project org.neo4j.springframework.data:spring-data-neo4j-rx-spring-boot-autoconfigure:jar:1.0.0-SNAPSHOT: Could not find artifact org.neo4j.driver:neo4j-java-driver-spring-boot-starter:jar:4.0.0-beta02 in spring-milestones (https://repo.spring.io/milestone)`

Saw in releases(https://github.com/neo4j/neo4j-java-driver-spring-boot-starter/releases) can only find `4.0.0-beta01` release.

Could you verify if its released or not?

**Comment by michael-simons** [comment]
🤦‍♂ You're correct. Give us a moment.
